# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aecf36ba2f27aff19a3eae453531c1951453312de6c83ca9453217cd242f960fe9790d135e37c9a32af4ff2ea01c458fa095760ee7582bffe9ca041a92e2ee79

test:
  secret_key_base: 42ccd39dce52867318d1562ff7073acf33d690ed1ce1b02327adc8166215b91a05c1a8976e205db728d2a76603b2b2db4ab8e2236dd769cd8d35b5c14a9441ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
